apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes 1;

    events {
        worker_connections 1024;
    }

    http {
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                         '$status $body_bytes_sent "$http_referer" '
                         '"$http_user_agent" "$http_x_forwarded_for"';

        access_log /var/log/nginx/access.log main;
        error_log /var/log/nginx/error.log debug;

        resolver 10.96.0.10 valid=5s;

        include /etc/nginx/conf.d/*.conf;
    }

  default.conf: |
    server {
        listen 80;

        location ~ ^/pod/(\d+) {
            set $pod_number $1;
            proxy_pass http://simple-api-$pod_number.simple-api-headless.default.svc.cluster.local:8080;
        }
    }
